### ISSUE TITLE
请求支持：暗色模式边框

### ISSUE THREAD

**Issue by chenbihao** [wish5115/obsidian-floating-settings#5]
在暗色模式下容易与背景融合在一起，分不清边界，
希望能跟原版一样带上浅色边框（或者有可选选项）

未开启插件：
![image](https://github.com/user-attachments/assets/8f94e14c-698c-4ef2-9569-b0f73d360e98)

开启插件：
![image](https://github.com/user-attachments/assets/e96f8673-68cc-4e3a-98ff-674c8280f453)

**Comment by wish5115** [comment]
感谢反馈！这个严格上说算是hoverEditor本身的问题，为避免hoverEditor升级可能带来的重复设置问题，暂不支持。

不过，你可以通过外部css样式实现，比如

```css
.theme-dark .floating-settings-popover[data-active-view-type="floating-settings"] {
    border: 1px solid #5a5858;
}
```
